version : '3.4'

networks:
    php-db:

services:
    php-container:
        container_name: php-container
        tty: true
        command: tail -f /dev/null
        ports:
            - 0.0.0.0:8000:8000
        environment:
            APACHE_DOCUMENT_ROOT: /app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - .:/app
        networks:
            - php-db
        depends_on:
            - db-container
    db-container:
        container_name: db-container
        tty: true
        ports:
            - 5432:5432
        image: postgres
        restart: always
        build:
            context: .
            dockerfile: ./docker/db/postgres/Dockerfile
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_HOST_AUTH_METHOD: md5
        networks:
            - php-db