#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
    path:     /login_check
    methods:  [POST]

api:
    path: /api
    controller: App\Controller\AuthController::api